MyWeb/MyWeb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),

]

MyWeb/music/urls.py
from django.conf.urls import url

from . import views

app_name = 'music'

urlpatterns = [

    # music
    url(r'^$', views.index, name='index'),

    # /music/712/
    url(r'^(?P<album_id>[0-9]+)/$', views.details, name='details'),

    # /music/favourite/
    url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),
]

MyWeb/music/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=100)
    song_title = models.CharField(max_length=100)
    favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

MyWeb/music/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from .models import Album

def index(request):
    all_albums = Album.objects.all()
    context = {'all_albums' : all_albums}
    return render(request, 'music/index.html', context)

def details(request, album_id):
    # try:
    #     album = Album.objects.get(pk=album_id)
    # except Album.DoesNotExist:
    #     raise Http404("Album does not exist!!")

    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album' : album})


def favourite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        select_song = album.song_set.get(pk=request.POST['song'])
        print select_song
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
                'album': album,
                'error_message': "You did not select valid song",
        })
    else:
        select_song.is_favourite = True
        select_song.save()
        return render(request, 'music/detail.html', {'album': album})

MyWeb/music/templates/music/detail.html
<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message %}
    <p><strong> {{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favourite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}"/>
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://www.freeiconspng.com/free-images/white-star-icon-13229"/>
            {% endif %}
        </label>
        <br>
    {% endfor%}
    <input type="submit" value="Favourite"/>
</form>

MyWeb/music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>Here are all my Albums</h3>
    {% if all_albums  %}
        <ul>
            {% for album in all_albums %}
            <li><a href="{% url 'music:details' album.id %}">{{ album.album_title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>N/A</h3>
    {% endif %}
</body>
</html>